# from: https://api.dhsprogram.com/rest/dhs/countries?returnFields=CountryName,DHS_CountryCode&f=html

country_list <- tibble::tribble(
  ~id,                        ~CountryName, ~DHS_CountryCode, ~Africa_tag,
   1L,                       "Afghanistan",             "AF",          0L,
   2L,                           "Albania",             "AL",          0L,
   3L,                            "Angola",             "AO",          1L,
   4L,                           "Armenia",             "AM",          0L,
   5L,                        "Azerbaijan",             "AZ",          0L,
   6L,                        "Bangladesh",             "BD",          0L,
   7L,                             "Benin",             "BJ",          1L,
   8L,                           "Bolivia",             "BO",          0L,
   9L,                          "Botswana",             "BT",          1L,
  10L,                            "Brazil",             "BR",          0L,
  11L,                      "Burkina Faso",             "BF",          1L,
  12L,                           "Burundi",             "BU",          1L,
  13L,                          "Cambodia",             "KH",          0L,
  14L,                          "Cameroon",             "CM",          1L,
  15L,                        "Cape Verde",             "CV",          1L,
  16L,          "Central African Republic",             "CF",          1L,
  17L,                              "Chad",             "TD",          1L,
  18L,                          "Colombia",             "CO",          0L,
  19L,                           "Comoros",             "KM",          1L,
  20L,                             "Congo",             "CG",          1L,
  21L,         "Congo Democratic Republic",             "CD",          1L,
  22L,                     "Cote d'Ivoire",             "CI",          1L,
  23L,                "Dominican Republic",             "DR",          0L,
  24L,                           "Ecuador",             "EC",          0L,
  25L,                             "Egypt",             "EG",          1L,
  26L,                       "El Salvador",             "ES",          0L,
  27L,                 "Equatorial Guinea",             "EK",          1L,
  28L,                           "Eritrea",             "ER",          1L,
  29L,                          "Ethiopia",             "ET",          1L,
  30L,                             "Gabon",             "GA",          1L,
  31L,                            "Gambia",             "GM",          1L,
  32L,                             "Ghana",             "GH",          1L,
  33L,                         "Guatemala",             "GU",          0L,
  34L,                            "Guinea",             "GN",          1L,
  35L,                            "Guyana",             "GY",          0L,
  36L,                             "Haiti",             "HT",          0L,
  37L,                          "Honduras",             "HN",          0L,
  38L,                             "India",             "IA",          0L,
  39L,                         "Indonesia",             "ID",          0L,
  40L,                            "Jordan",             "JO",          0L,
  41L,                        "Kazakhstan",             "KK",          0L,
  42L,                             "Kenya",             "KE",          1L,
  43L,                   "Kyrgyz Republic",             "KY",          0L,
  44L,  "Lao People's Democratic Republic",             "LA",          0L,
  45L,                           "Lesotho",             "LS",          1L,
  46L,                           "Liberia",             "LB",          1L,
  47L,                        "Madagascar",             "MD",          1L,
  48L,                            "Malawi",             "MW",          1L,
  49L,                          "Maldives",             "MV",          0L,
  50L,                              "Mali",             "ML",          1L,
  51L,                        "Mauritania",             "MR",          1L,
  52L,                            "Mexico",             "MX",          0L,
  53L,                           "Moldova",             "MB",          0L,
  54L,                           "Morocco",             "MA",          1L,
  55L,                        "Mozambique",             "MZ",          1L,
  56L,                           "Myanmar",             "MM",          0L,
  57L,                           "Namibia",             "NM",          1L,
  58L,                             "Nepal",             "NP",          0L,
  59L,                         "Nicaragua",             "NC",          0L,
  60L,                             "Niger",             "NI",          1L,
  61L,                           "Nigeria",             "NG",          1L,
  62L,                          "Pakistan",             "PK",          0L,
  63L,                  "Papua New Guinea",             "PG",          0L,
  64L,                          "Paraguay",             "PY",          0L,
  65L,                              "Peru",             "PE",          0L,
  66L,                       "Philippines",             "PH",          0L,
  67L,                            "Rwanda",             "RW",          1L,
  68L,                             "Samoa",             "WS",          0L,
  69L,             "Sao Tome and Principe",             "ST",          0L,
  70L,                           "Senegal",             "SN",          1L,
  71L,                      "Sierra Leone",             "SL",          1L,
  72L,                      "South Africa",             "ZA",          1L,
  73L,                         "Sri Lanka",             "LK",          0L,
  74L,                             "Sudan",             "SD",          1L,
  75L,                         "Swaziland",             "SZ",          1L,
  76L,                        "Tajikistan",             "TJ",          0L,
  77L,                          "Tanzania",             "TZ",          1L,
  78L,                          "Thailand",             "TH",          0L,
  79L,                       "Timor-Leste",             "TL",          0L,
  80L,                              "Togo",             "TG",          1L,
  81L,               "Trinidad and Tobago",             "TT",          0L,
  82L,                           "Tunisia",             "TN",          1L,
  83L,                            "Turkey",             "TR",          0L,
  84L,                      "Turkmenistan",             "TM",          0L,
  85L,                            "Uganda",             "UG",          1L,
  86L,                           "Ukraine",             "UA",          0L,
  87L,                        "Uzbekistan",             "UZ",          0L,
  88L,                           "Vietnam",             "VN",          0L,
  89L,                             "Yemen",             "YE",          0L,
  90L,                            "Zambia",             "ZM",          1L,
  91L,                          "Zimbabwe",             "ZW",          1L
  )
